apiVersion: v1
kind: Service
metadata: 
  name: wordpress-service  
  namespace: 1239563-1994580-1994821-1522625
  labels:
    app: wordpress
    tier: frontend
    env: dev
spec: 
  selector: 
    app: wordpress
    tier: frontend
    env: dev
  ports: 
  - port: 80
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: 1239563-1994580-1994821-1522625
  labels: 
    app: wordpress
    tier: frontend
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
      env: dev
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
        env: dev
    spec: 
      containers: 
      - name: wordpress
        image: wordpress
        ports: 
        - containerPort: 80
          name: wordpress 
        env: 
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress