apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: backend
    env: accept
  name: nginx-deployment6
  namespace: jpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: backend
      env: accept
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
        env: accept
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
