version: "3"

services:
  php:
    build: './php/'
    networks:
      - backend
    volumes:
      - ./monsite/html:/srv/htdocs
  apache:
    build:  './monsite/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./monsite/html:/srv/htdocs # lien avec le répertoire Apache
networks:
  frontend:
  backend: