apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: jpd
  labels:
    app: nginx
    tier: frontend
    env: unit
spec:
  selector:
    app: nginx
    tier: frontend
    env: unit
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30100
  type: NodePort
