apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: jpd
  labels:
    app: nginx
    tier: frontend
    env: unit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      env: unit
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        env: unit
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello
        ports:
        - containerPort: 80
