FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /source

COPY . .
RUN dotnet publish -c release -o /app

FROM mcr.microsoft.com/dotnet/runtime:3.1
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["./premier-conteneur-csharp"]
