apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-1995222-1996034-1995274
  namespace: "1995222-1996034-1995274"
  labels:
    app: wordpress
    tier: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.100.1.6
    path: "/srv/exports/1995222-1996034-1995274/TP3/mysql-1995222-1996034-1995274"