apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-mysql-1995222-1996034-1995274
  namespace: "1995222-1996034-1995274"
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: "pv-nfs-mysql-1995222-1996034-1995274"    