apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-1995222-1996034-1995274  # va etre utilisé pour DB_HOST dans le dep-wordpress
  namespace: "1995222-1996034-1995274"  
  labels:                 
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None