apiVersion: v1
kind : Pod
metadata: 
  name: wp
spec:
  containers:
  - image: wordpress
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_USER
      value: wordpress
    - name: WORDPRESS_DB_PASSWORD
      value: wordpress
   
  - image: mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: mysqlpwd
    - name: MYSQL_DATABASE
      value: wordpress
    - name: MYSQL_USER
      value: wordpress
    - name: MYSQL_PASSWORD
      value: wordpress
    
    
    
