apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-exercice-jpd
spec:
  storageClassName: manuel
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs: 
    server: 10.100.2.90
    path: "/srv/exports/jpd/nginx01"
